### ISSUE TITLE
Use the example field

### ISSUE THREAD

**Issue by liekelotte** [esciencecenter-digital-skills/lesson-R-packaging#46]
I think it would be nice to let users try to use the example field in roxygen2, as an optional in the exercise! Is there a reason not to? If they need to use markdown formatting they will also have used that in the workshop already. And examples are very valuable for other users.

**Comment by PabRod** [comment]
There is a reason, indeed: roxygen2 examples do not coexist peacefully with unit tests.

The problem is that they are much more than examples: they are tests as well, in the sense that are run and can trigger a failure. A trick is to surround them by `\dontrun{<example>}`. This renders them into just text for the help menu.
